default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: adventure_map_development

test: &test
  <<: *default
  database: adventure_map_test

production:
  <<: *default
  database: adventure_map_production
  username: deploy
  password: deploy

cucumber:
  <<: *test
